### ISSUE TITLE
mtucker01752's checklist

### ISSUE THREAD

**Issue by markrtucker** [githubteacher/dev-oct-13#11]
## Class checklist
- [x] Create a branch
- [x] Create an issue
- [x] Add commits
- [x] Open a pull request
- [x] Collaborate/more commits
- [x] Merge pull request
# Heading 1
