### ISSUE TITLE
maacnis's checklist

### ISSUE THREAD

**Issue by maacnis** [githubteacher/dev-oct-13#14]
## Class Checklist
- [x] Create an Issue
- [x] Create a Branch
- [x] Make Commits
- [x] Open a pull request
- [x] Collaborate
- [x] Merge pull request
