### ISSUE TITLE
mpgrill's class checklist

### ISSUE THREAD

**Issue by mpgrill** [githubteacher/dev-oct-13#15]
# Class Checklist
- [x] Create an issue
- [x] Create a branch
- [x] Add commits
- [x] Open a pull request
- [x] Collaborate/more commits
- [ ] Merge pull request
