### ISSUE TITLE
ikkhan checklist

### ISSUE THREAD

**Issue by ikkhan** [githubteacher/dev-oct-13#18]
## Class Checklist
- [x] Create an issue
- [x] Create an branch
- [ ] Make commits
- [ ] Open Pull request
- [ ] Collaborate
- [ ] Merge pull request
