### ISSUE TITLE
dataacumen-checklist

### ISSUE THREAD

**Issue by dataacumen** [githubteacher/dev-oct-13#19]
# Class Checklist
- [x] Create Issue
- [x] Create a branch
- [x] Add commits
- [x] Open a pull request
- [ ] Collaborate/more commits
- [ ] Merge pull request
