### ISSUE TITLE
geoemm's class checklist 

### ISSUE THREAD

**Issue by geoemm** [githubteacher/dev-oct-13#20]
# Class Checklist
- [x] Create a branch
- [ ] Add commits
- [ ] Open a pull request
- [ ] Collaborate/more commits
- [ ] Merge pull request
