### ISSUE TITLE
silvpas's class checklist

### ISSUE THREAD

**Issue by silvpas** [githubteacher/dev-oct-13#21]
# Class Checklist
- [x] Create a branch
- [x] Add commits
- [ ] Merge pull request
  ❇️ 
- [x] Open a pull request
- [ ] Collaborate/more commits
