### ISSUE TITLE
chesterbelloc's class checklist

### ISSUE THREAD

**Issue by davidhouts** [githubteacher/dev-oct-13#22]
## Class Checklist
- [x] Create and issue
- [x] Create a branch
- [] Make commits
- [] Open a pull request
- [] Collaborate!
- [] Merge pull request
- [x] Have a great time!
