### ISSUE TITLE
guri46's checklist

### ISSUE THREAD

**Issue by codegemini** [githubteacher/dev-oct-13#23]
## Training Checklist
- [X] Create an Issue
- [X] Create a Branch
- [x] Make Commits
- [x] Open a pull request
- [x] Collaborate/more commits
- [x] Merge pull request
- [x] Have a great time! 🎱
