### ISSUE TITLE
adrianz's class checklist

### ISSUE THREAD

**Issue by adrianz** [githubteacher/dev-oct-13#24]
# Class Checklist
- [x] Create a branch
- [x] Add commits
- [x] Open a pull request
- [x] Collaborate/more commits
- [x] Merge pull request
