### ISSUE TITLE
vharsh's checklist

### ISSUE THREAD

**Issue by vharsh** [githubteacher/dev-oct-13#25]

**Comment by vharsh** [comment]
- [x] Having funn :)
- [x] Created an issue
- [x] cloned it to my laptop
- [x] configured git
- [ ] Create pull request
- [ ] Merge PR
- [ ] Collaborate
