### ISSUE TITLE
RMBloom's class ToDo list

### ISSUE THREAD

**Issue by RMBloom** [githubteacher/dev-oct-13#27]
# Class Checklist
- [x] Create a branch
- [x] Add commits
- [x] Open a pull request
- [x] Collaborate/more commits
- [x] Merge pull request
- [x] Have a great time! ❇️
