### ISSUE TITLE
trinoeg8's class checklist

### ISSUE THREAD

**Issue by 8geonirt** [githubteacher/dev-oct-13#28]
# Class Checklist
- [x] Create an issue
- [x] Create a branch
- [x] Add commits
- [x] Open a pull request
- [ ] Collaborate/more commits
- [ ] Merge pull request
- [ ] Collaborate!
- [x] Have a great time! 🎇
