### ISSUE TITLE
Grace's Checklist

### ISSUE THREAD

**Issue by gracepark** [githubteacher/dev-oct-13#30]
# Class Checklist
- [x] Create a branch
- [x] Add commits
- [x] Open a pull request
- [x] Collaborate/more commits
- [x] Merge pull request
