### ISSUE TITLE
Thomas-Squared's Class Checklist

### ISSUE THREAD

**Issue by Thomas-Squared** [githubteacher/dev-oct-13#31]
## Class Checklist - [ ] Create a branch
- [x] Create a new issue
- [x] Create a branch
- [x] Add commits
- [x] Open a pull request
- [x] Collaborate/more commits
- [x] Merge pull request
- [ ] Have a great time!
