### ISSUE TITLE
codegagan's class checklist

### ISSUE THREAD

**Issue by codegagan** [githubteacher/dev-oct-13#32]
# Class Checklist
- [x] Create a branch
- [x] Add commits
- [ ] Collaborate/more commits
- [ ] Open a pull request
- [ ] Merge pull request
- [ ] pull in latest changes after pull request

🔢
