### ISSUE TITLE
Class Checklist

### ISSUE THREAD

**Issue by DanCollinz** [githubteacher/dev-oct-13#35]
# Class Checklist
- [ ] Create a branch
- [ ] Add commits
- [ ] Open a pull request
- [ ] Collaborate/more commits
- [ ] Merge pull request
  :fire:
