### ISSUE TITLE
alexinseattle todo list

### ISSUE THREAD

**Issue by alexinseattle** [githubteacher/dev-oct-13#36]
## Todo List
- [x] create an issue
- [x] create a branch
- [x] make commits
- [x] open a pull request
- [x] collborate
- [x] merge pull request

☔️
