### ISSUE TITLE
panw-sp's checklist

### ISSUE THREAD

**Issue by PANW-SP** [githubteacher/dev-oct-13#39]
## Class Checklist
- [x] Create an Issue 
- [x] Create a Branch
- [ ] Make Commits
- [ ] Open a pull request
- [ ] Collaborate
- [ ] Merge pull request
- [ ] Have a great time !
