### ISSUE TITLE
nilmind's class checklist

### ISSUE THREAD

**Issue by ghost** [githubteacher/dev-oct-13#41]
## Create an Issue
- [x] Create a Branch
- [x] Make commits
- [ ] Open a pull request
- [ ] Collaborate!
- [ ] Merge pull request
- [ ] Have a great time! 🎇
