### ISSUE TITLE
boerst class checklist

### ISSUE THREAD

**Issue by boerst** [githubteacher/dev-oct-13#43]
## My awesome checklist
- [x] Pick a city
- [ ] Pick a restaurant
- [ ] Pick an outfit
- [ ] invite your friends
- [ ] align on a date and time
- [ ] go to restaurant
- [ ] HAVE FUN
