### ISSUE TITLE
pralat's class checklist

### ISSUE THREAD

**Issue by pralat** [githubteacher/dev-oct-13#44]
## Class Checklist
- [ ] Create a branch
- [ ] Add commits
- [ ] Open a pull request
- [ ] Collaborate/more commits
- [ ] Merge pull request
